### ISSUE TITLE
Lead by example

### ISSUE THREAD

**Issue by Acid-Override** [ubam/marketing#1]
First topic for fun.  @exar_kun and I believe we should change the following in our community and lead the other communities by good example in the following items:

1. Calling Ubuntu (and  Ubuntu Touch) "Linux".  It is not linux, it runs the linux kernel.  Calling it 'Ubuntu Linux" is both incorrect and also has bad marketing images in it, I"m sorry to say.  It conjures images of 'geeks' and 'nerds'.  And that brings me to the next point:

2. Complete removal of the terms 'geeks' and 'nerds' from our vocabulary and marketing.  A geek or a nerd is a bad term that insults the person and should not be connected to something as prestigious and important and revolutionary as the UBports project.

3. Pronunciation of Ubuntu - we simply have to fix this one and help others too.  

Thank you!

**Comment by PeterNerlich** [comment]
This issue was moved to ubam/ubfr-docs#16
